services:
    postgres:
        image: 'postgres:latest'
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - budgetbook-data:/var/lib/postgresql/data

volumes:
    budgetbook-data:
